language: php
php:
  - '7.0'
  - '5.6'
  - '5.5'
  - 'hhvm'
install:
  - curl -s http://getcomposer.org/installer | php
  - php --no-php-ini -d allow_url_fopen=On -d detect_unicode=Off composer.phar install --no-interaction
script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

